### ISSUE TITLE
new ideas to improve "Masir"

### ISSUE THREAD

**Issue by shayanfpg9** [kasraghoreyshi/maseer#1]
Hi,
At the first I should say thanks for helping to the iranian developers.
But I think your app has a little problems and for that it can't compete with [roadmap.sh](https://roadmap.sh) or another same tools,
so I have some ideas to improve it

1. nesting design:
the nesting desing like the created mind maps with XMind or another tools,
it need the smaller size and you can add a lot of new concepts as soon as possible but it dosen't get a lot of size

2. completed option:
You can add the the completed badge in the description part and connect it to IndexedDB to cache the datas,
when user complete a concept they can ticked it and then it's style changing to ticked 

3. add the educational resources:
You can connect the description part to the fa/en tutorials or educational resouces,
after that user can learn the concepts easyer;
actually you did it but not completely for all of the concepts

I think it's a good way to make the smarter developers in the future

thanks a lot for your fantastic works ♥

**Comment by kasraghoreyshi** [comment]
Hi, I appreciate and agree with your ideas. I abandoned this project for now but will implement your ideas if I were to recreate it. Thanks!
